export const Universities = [
	{ name: "Abia State University", value: "Abia State University" },
	{
		name: "Abubakar Tafawa Balewa University",
		value: "Abubakar Tafawa Balewa University",
	},
	{ name: "Achievers University, Owo", value: "Achievers University, Owo" },
	{ name: "Adamawa State University", value: "Adamawa State University" },
	{ name: "Adekunle Ajasin University", value: "Adekunle Ajasin University" },
	{ name: "Adeleke University", value: "Adeleke University" },
	{
		name: "Admiralty University of Nigeria",
		value: "Admiralty University of Nigeria",
	},
	{ name: "Afe Babalola University", value: "Afe Babalola University" },
	{
		name: "African University of Science and Technology",
		value: "African University of Science and Technology",
	},
	{ name: "Ahmadu Bello University", value: "Ahmadu Bello University" },
	{ name: "Ajayi Crowther University", value: "Ajayi Crowther University" },
	{ name: "Akwa Ibom State University", value: "Akwa Ibom State University" },
	{
		name: "Alex Ekwueme Federal University",
		value: "Alex Ekwueme Federal University",
	},
	{ name: "Al-Hikmah University", value: "Al-Hikmah University" },
	{
		name: "Al-Qalam University, Katsina",
		value: "Al-Qalam University, Katsina",
	},
	{ name: "Ambrose Alli University", value: "Ambrose Alli University" },
	{
		name: "American University of Nigeria",
		value: "American University of Nigeria",
	},
	{ name: "Anchor University, Lagos", value: "Anchor University, Lagos" },
	{ name: "Arthur Jarvis University", value: "Arthur Jarvis University" },
	{ name: "Atiba University", value: "Atiba University" },
	{ name: "Augustine University", value: "Augustine University" },
	{ name: "Babcock University", value: "Babcock University" },
	{
		name: "Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti",
		value:
			"Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti",
	},
	{ name: "Bauchi State University", value: "Bauchi State University" },
	{ name: "Bayero University Kano", value: "Bayero University Kano" },
	{ name: "Baze University", value: "Baze University" },
	{
		name: "Bells University of Technology",
		value: "Bells University of Technology",
	},
	{ name: "Benson Idahosa University", value: "Benson Idahosa University" },
	{ name: "Benue State University", value: "Benue State University" },
	{ name: "Bingham University", value: "Bingham University" },
	{ name: "Borno State University", value: "Borno State University" },
	{ name: "Bowen University", value: "Bowen University" },
	{ name: "Caleb University", value: "Caleb University" },
	{ name: "Caritas University", value: "Caritas University" },
	{ name: "Chrisland University", value: "Chrisland University" },
	{ name: "Christopher University", value: "Christopher University" },
	{
		name: "Chukwuemeka Odumegwu Ojukwu University",
		value: "Chukwuemeka Odumegwu Ojukwu University",
	},
	{ name: "Clifford University", value: "Clifford University" },
	{ name: "Coal City University", value: "Coal City University" },
	{ name: "Covenant University", value: "Covenant University" },
	{ name: "Crawford University", value: "Crawford University" },
	{
		name: "Crescent University, Abeokuta",
		value: "Crescent University, Abeokuta",
	},
	{ name: "Crown Hill University", value: "Crown Hill University" },
	{
		name: "Delta State University, Abraka",
		value: "Delta State University, Abraka",
	},
	{
		name: "Dominican University, Ibadan",
		value: "Dominican University, Ibadan",
	},
	{ name: "Ebonyi State University", value: "Ebonyi State University" },
	{
		name: "Edo State University Uzairue",
		value: "Edo State University Uzairue",
	},
	{ name: "Edwin Clark University", value: "Edwin Clark University" },
	{
		name: "Ekiti State University, Ado Ekiti",
		value: "Ekiti State University, Ado Ekiti",
	},
	{
		name: "Eko University of Medical and Health Sciences",
		value: "Eko University of Medical and Health Sciences",
	},
	{ name: "Elizade University", value: "Elizade University" },
	{
		name: "Enugu State University of Science and Technology",
		value: "Enugu State University of Science and Technology",
	},
	{ name: "Evangel University, Akaeze", value: "Evangel University, Akaeze" },
	{
		name: "Federal University of Agriculture, Abeokuta",
		value: "Federal University of Agriculture, Abeokuta",
	},
	{
		name: "Federal University of Petroleum Resources",
		value: "Federal University of Petroleum Resources",
	},
	{
		name: "Federal University of Technology, Akure",
		value: "Federal University of Technology, Akure",
	},
	{
		name: "Federal University of Technology, Minna",
		value: "Federal University of Technology, Minna",
	},
	{
		name: "Federal University of Technology, Owerri",
		value: "Federal University of Technology, Owerri",
	},
	{
		name: "Federal University, Birnin Kebbi",
		value: "Federal University, Birnin Kebbi",
	},
	{ name: "Federal University, Dutse", value: "Federal University, Dutse" },
	{
		name: "Federal University, Dutsin-Ma",
		value: "Federal University, Dutsin-Ma",
	},
	{ name: "Federal University, Gashua", value: "Federal University, Gashua" },
	{ name: "Federal University, Gusau", value: "Federal University, Gusau" },
	{ name: "Federal University, Kashere", value: "Federal University, Kashere" },
	{ name: "Federal University, Lafia", value: "Federal University, Lafia" },
	{ name: "Federal University, Lokoja", value: "Federal University, Lokoja" },
	{ name: "Federal University, Otuoke", value: "Federal University, Otuoke" },
	{
		name: "Federal University, Oye-Ekiti",
		value: "Federal University, Oye-Ekiti",
	},
	{ name: "Federal University, Wukari", value: "Federal University, Wukari" },
	{ name: "Fountain University, Osogbo", value: "Fountain University, Osogbo" },
	{ name: "Glorious Vision University", value: "Glorious Vision University" },
	{ name: "Godfrey Okoye University", value: "Godfrey Okoye University" },
	{ name: "Gombe State University", value: "Gombe State University" },
	{
		name: "Gombe State University of Science and Technology",
		value: "Gombe State University of Science and Technology",
	},
	{ name: "Gregory University, Uturu", value: "Gregory University, Uturu" },
	{
		name: "Hallmark University, Ijebu-Itele",
		value: "Hallmark University, Ijebu-Itele",
	},
	{ name: "Hezekiah University", value: "Hezekiah University" },
	{
		name: "Ibrahim Badamasi Babangida University",
		value: "Ibrahim Badamasi Babangida University",
	},
	{ name: "Igbinedion University Okada", value: "Igbinedion University Okada" },
	{
		name: "Ignatius Ajuru University of Education",
		value: "Ignatius Ajuru University of Education",
	},
	{ name: "Imo State University", value: "Imo State University" },
	{
		name: "Joseph Ayo Babalola University",
		value: "Joseph Ayo Babalola University",
	},
	{
		name: "Joseph Sarwuan Tarkaa University",
		value: "Joseph Sarwuan Tarkaa University",
	},
	{ name: "Kaduna State University", value: "Kaduna State University" },
	{
		name: "Kano University of Science and Technology",
		value: "Kano University of Science and Technology",
	},
	{ name: "Karl Kuum University", value: "Karl Kuum University" },
	{
		name: "Kebbi State University of Science and Technology",
		value: "Kebbi State University of Science and Technology",
	},
	{ name: "Kings University", value: "Kings University" },
	{
		name: "Kingsley Ozumba Mbadiwe University",
		value: "Kingsley Ozumba Mbadiwe University",
	},
	{ name: "Kola Daisi University", value: "Kola Daisi University" },
	{ name: "Kwara State University", value: "Kwara State University" },
	{
		name: "Kwararafa University, Wukari",
		value: "Kwararafa University, Wukari",
	},
	{
		name: "Ladoke Akintola University of Technology",
		value: "Ladoke Akintola University of Technology",
	},
	{ name: "Lagos State University", value: "Lagos State University" },
	{ name: "Landmark University", value: "Landmark University" },
	{ name: "Lead City University", value: "Lead City University" },
	{ name: "Legacy University, Okija", value: "Legacy University, Okija" },
	{ name: "Madonna University, Nigeria", value: "Madonna University, Nigeria" },
	{ name: "Mcpherson University", value: "Mcpherson University" },
	{
		name: "Mewar International University",
		value: "Mewar International University",
	},
	{
		name: "Michael and Cecilia Ibru University",
		value: "Michael and Cecilia Ibru University",
	},
	{
		name: "Michael Okpara University of Agriculture",
		value: "Michael Okpara University of Agriculture",
	},
	{
		name: "Modibbo Adama University, Yola",
		value: "Modibbo Adama University, Yola",
	},
	{
		name: "Moshood Abiola Polytechnic, Abeokuta",
		value: "Moshood Abiola Polytechnic, Abeokuta",
	},
	{ name: "Mountain Top University", value: "Mountain Top University" },
	{ name: "Nasarawa State University", value: "Nasarawa State University" },
	{ name: "Niger Delta University", value: "Niger Delta University" },
	{
		name: "Nigerian Maritime University, Okerenkoko",
		value: "Nigerian Maritime University, Okerenkoko",
	},
	{ name: "Nile University of Nigeria", value: "Nile University of Nigeria" },
	{ name: "Nnamdi Azikiwe University", value: "Nnamdi Azikiwe University" },
	{ name: "Northwest University, Kano", value: "Northwest University, Kano" },
	{ name: "Novena University", value: "Novena University" },
	{ name: "Obafemi Awolowo University", value: "Obafemi Awolowo University" },
	{ name: "Obong University", value: "Obong University" },
	{ name: "Oduduwa University", value: "Oduduwa University" },
	{ name: "Olabisi Onabanjo University", value: "Olabisi Onabanjo University" },
	{
		name: "Ondo State University of Science and Technology",
		value: "Ondo State University of Science and Technology",
	},
	{ name: "Osun State University", value: "Osun State University" },
	{
		name: "PAMO University of Medical Sciences",
		value: "PAMO University of Medical Sciences",
	},
	{ name: "Pan-Atlantic University", value: "Pan-Atlantic University" },
	{ name: "Paul University", value: "Paul University" },
	{ name: "Peaceland University Enugu", value: "Peaceland University Enugu" },
	{ name: "Plateau State University", value: "Plateau State University" },
	{
		name: "Precious Cornerstone University",
		value: "Precious Cornerstone University",
	},
	{
		name: "Prince Abubakar Audu University",
		value: "Prince Abubakar Audu University",
	},
	{ name: "Redeemer's University", value: "Redeemer's University" },
	{ name: "Renaissance University", value: "Renaissance University" },
	{ name: "Rhema University", value: "Rhema University" },
	{ name: "Ritman University", value: "Ritman University" },
	{ name: "Rivers State University", value: "Rivers State University" },
	{ name: "Salem University", value: "Salem University" },
	{ name: "Skyline University Nigeria", value: "Skyline University Nigeria" },
	{ name: "Sokoto State University", value: "Sokoto State University" },
	{
		name: "Southwestern University, Nigeria",
		value: "Southwestern University, Nigeria",
	},
	{ name: "Spiritan University Nneochi", value: "Spiritan University Nneochi" },
	{ name: "Sule Lamido University", value: "Sule Lamido University" },
	{ name: "Summit University Offa", value: "Summit University Offa" },
	{
		name: "Tai Solarin University of Education",
		value: "Tai Solarin University of Education",
	},
	{ name: "Tansian University", value: "Tansian University" },
	{ name: "Taraba State University", value: "Taraba State University" },
	{ name: "The Technical University", value: "The Technical University" },
	{ name: "Thomas Adewumi University", value: "Thomas Adewumi University" },
	{
		name: "Umaru Musa Yar'Adua University",
		value: "Umaru Musa Yar'Adua University",
	},
	{ name: "University of Abuja", value: "University of Abuja" },
	{ name: "University of Africa", value: "University of Africa" },
	{ name: "University of Benin", value: "University of Benin" },
	{ name: "University of Calabar", value: "University of Calabar" },
	{
		name: "University of Cross River State",
		value: "University of Cross River State",
	},
	{ name: "University of Ibadan", value: "University of Ibadan" },
	{ name: "University of Ilorin", value: "University of Ilorin" },
	{ name: "University of Jos", value: "University of Jos" },
	{ name: "University of Lagos", value: "University of Lagos" },
	{ name: "University of Maiduguri", value: "University of Maiduguri" },
	{
		name: "University of Medical Sciences",
		value: "University of Medical Sciences",
	},
	{ name: "University of Mkar", value: "University of Mkar" },
	{ name: "University of Nigeria", value: "University of Nigeria" },
	{ name: "University of Port Harcourt", value: "University of Port Harcourt" },
	{ name: "University of Uyo", value: "University of Uyo" },
	{ name: "Usmanu Danfodio University", value: "Usmanu Danfodio University" },
	{ name: "Veritas University", value: "Veritas University" },
	{ name: "Wellspring University", value: "Wellspring University" },
	{
		name: "Wesley University of Science and Technology",
		value: "Wesley University of Science and Technology",
	},
	{ name: "Western Delta University", value: "Western Delta University" },
	{ name: "Yobe State University", value: "Yobe State University" },
	{ name: "Zamfara State University", value: "Zamfara State University" },
];

export const levels = [
	{
		name: "100",
		value: "100",
	},
	{ name: "200", value: "200" },
	{ name: "300", value: "300" },
	{ name: "400", value: "400" },
	{ name: "500", value: "500" },
	{ name: "600", value: "600" },
];
